### ISSUE TITLE
Komplettierung Sachsen, insb. Erzgebirge

### ISSUE THREAD

**Issue by embix** [marhei/TrainCompany-Data#481]
## Was wird hinzugefügt?

Overhaul und Streckenkomplettierung in Sachsen (analog zu dem Detailgrad wie das in Bayern schon sehr schön umgesetzt ist)

## Art der Erweiterung
[x] Strecke
[?] Zug (bei Bedarf)
[x] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details

Overhaul:

- [x] #504 Chemnitz - Döbeln
- [x] #504 Döbeln - Riesa

Neu:

- [x] Nebenbahn Heidenau - Altenberg (Erzgebirge)
- [x] #654 Hauptstrecke Leipzig - Delitzsch - Bitterfeld - Dessau
- [x] #505 Hauptstrecke Bischofswerda - Neukirch (Lausitz) - Ebersbach - Zittau (-Radek nad Nisou)
- [x] #482 Hauptstrecke Schwarzenberg - Zwickau (Obererzgebirgische Eisenbahn)
- [x] #493 Nebenbahn Flöha - Annaberg-Buchholz (-Vejprty (CZ))
- [x] #482 Nebenbahn Chemnitz - Aue (Würschnitztalbahn)
- [x] #482 Nebenbahn Aue - Schwarzenberg (Erzgebirge) - Potucky (CZ)
- [x] #493 Nebenbahn Schwarzenberg - Annaberg-Buchholz
- [x] #495 Nebenbahn Flöha - Pockau-Lengefeld - Neuhausen (Flöhatahlbahn)
- [x] #505 Nebenbahn Pirna - Stolpen - Neustadt (Sachsen) (Teil der Süd-Lausitzer Bahn)
- [x] #505 Nebenbahn Bad Schandau - Sebnitz - Neustadt (Sachsen)
- [x] #505 Nebenbahn optional Ebersbach - Rumburk
- [x] #505 Nebenbahn optional Sebnitz - Dolní Poustevna (CZ) (- Mikulásovice (CZ)🕵️ - Rumburk (CZ))
- [x] #723 Nebenstrecke optional Nossen - Freiberg - Holzhau ( Rest bis ~~Moldava v Krušných horách~~ wurde stillgelegt) (auch z.T. NREC, 🕵️)
- [x] #729 Nebenbahn Zwickau - Falkenstein - Zwotental - Klingenthal - Kraslice (CZ) - Sokolov (CZ)
- [x] #730 Nebenbahn Zwotental - Adorf
- [x] #730 Herlasgrün - Falkenstein
- [x] #730 Nebenbahn optional Muldenberg-Schönheide Ost (Teil von Chemnitz-Adorf)
- [x] #737 Nebenbahn optional Zittau - Krzevina Zgorzelecka (PL) - Görlitz
- ~~Nebenbahn optional Görlitz - Zgorzelec (PL)~~

Jobs für Strecken:

- [x] #730 VBG RB1 Zwickau-Falkenstein-Zwotental-Klingenthal-Kraslice-Sokolov-KarlovyVary
- [x] #730 VBG RB5 Meltheuer-Plauen-Herlasgrün-Falkenstein-Zwotental-Klingenthal-Sokolov-KarlovyVary
- [x] #730 Adorf-Zwotental: Sonderzug [Musikwinkelexpress](https://oveb.de/musikwinkel-express/)
- [x] #742 Nossen-Freiberg-Holzhau

Evtl. später als Follow-Up, sofern reaktiviert:

-  Nebenstrecke Riesa-Nossen (gehört der [Nossen-Riesaer Eisenbahn-Compagnie GmbH](http://www.nre-compagnie.de), NREC - nicht im Trassenfinder 🕵️) - aktuell größtenteils stillgelegt 
-  Nebenstrecke Dürrröhrsdorf - Arnsdorf (🕵️) seit 2007 stillgelegt 😞
- Nebenbahn Neustadt (Sachsen) - Neukirch (Lausitz) (Teil von Bautzen - Bad Schandau, nicht im Trassenfinder 🕵️) Strecke aktuell unterbrochen, Betrieb nur zwischen Steinbruch Oberottendorf und Neukirch

**Comment by embix** [comment]
define: feature creep 😅
